# Generated by Django 5.0.7 on 2024-08-04 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seniorapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seniorcitizen',
            options={'managed': False},
        ),
    ]
