# Generated by Django 5.0.7 on 2024-08-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seniorapp', '0002_alter_seniorcitizen_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('created_by', models.CharField(choices=[('Admin', 'Admin'), ('HealthWorker', 'HealthWorker')], max_length=15)),
                ('creator_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcement_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_posted', models.DateField()),
                ('posted_by', models.CharField(choices=[('Admin', 'Admin'), ('HealthWorker', 'HealthWorker')], max_length=15)),
                ('poster_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Announcement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HealthWorker',
            fields=[
                ('worker_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'HealthWorker',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PredictiveAnalytics',
            fields=[
                ('analytics_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('results', models.TextField()),
                ('created_by', models.CharField(choices=[('Admin', 'Admin'), ('HealthWorker', 'HealthWorker')], max_length=15)),
                ('creator_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'PredictiveAnalytics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('Admin', 'Admin'), ('HealthWorker', 'HealthWorker')], max_length=15)),
                ('user_id', models.IntegerField()),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SMSNotification',
            fields=[
                ('sms_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipient_phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('sent_by', models.CharField(choices=[('Admin', 'Admin'), ('HealthWorker', 'HealthWorker')], max_length=15)),
                ('sender_id', models.IntegerField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'SMSNotification',
                'managed': False,
            },
        ),
    ]
