# Generated by Django 5.1 on 2024-08-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seniorapp', '0004_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProfiling',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('age', models.IntegerField()),
                ('lifestyle_diet', models.BooleanField(default=False)),
                ('lifestyle_exercise', models.BooleanField(default=False)),
                ('lifestyle_others', models.CharField(blank=True, max_length=255, null=True)),
                ('medical_history_past_illness', models.TextField(blank=True, null=True)),
                ('medical_history_treatments', models.TextField(blank=True, null=True)),
                ('medical_history_ongoing_medications', models.TextField(blank=True, null=True)),
                ('medical_history_checkups', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'DataProfiling',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SummaryCounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_count', models.IntegerField()),
                ('activity_count', models.IntegerField()),
                ('healthworker_count', models.IntegerField()),
                ('smsnotification_count', models.IntegerField()),
            ],
            options={
                'db_table': 'summary_counts',
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='WeeklySMSSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=255)),
                ('sms_sent_count', models.IntegerField()),
            ],
            options={
                'db_table': 'weekly_sms_sent',
                'managed': False,
            },
        ),
    ]
