# Generated by Django 5.1 on 2024-10-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seniorapp', '0005_dataprofiling_summarycounts_weeklysmssent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProfilingView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('age', models.IntegerField()),
                ('lifestyle_diet', models.BooleanField(default=False)),
                ('lifestyle_exercise', models.BooleanField(default=False)),
                ('lifestyle_others', models.CharField(blank=True, max_length=255, null=True)),
                ('medical_history_past_illness', models.TextField(blank=True, null=True)),
                ('medical_history_treatments', models.TextField(blank=True, null=True)),
                ('medical_history_ongoing_medications', models.TextField(blank=True, null=True)),
                ('medical_history_checkups', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('created_date', models.DateField()),
                ('created_week', models.CharField(max_length=10)),
                ('created_month', models.CharField(max_length=10)),
                ('created_year', models.CharField(max_length=10)),
                ('created_week_number', models.IntegerField()),
            ],
            options={
                'db_table': 'dataprofiling_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PredictiveAnalyticsView',
            fields=[
                ('analytics_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('results', models.TextField()),
                ('created_by', models.CharField(choices=[('Admin', 'Admin'), ('HealthWorker', 'HealthWorker')], max_length=15)),
                ('creator_id', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('created_date', models.DateField()),
                ('created_week', models.CharField(max_length=10)),
                ('created_month', models.CharField(max_length=10)),
                ('created_year', models.CharField(max_length=10)),
                ('created_week_number', models.IntegerField()),
            ],
            options={
                'db_table': 'predictiveanalytics_view',
                'managed': False,
            },
        ),
    ]
