# Generated by Django 5.1 on 2024-10-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seniorapp', '0006_dataprofilingview_predictiveanalyticsview'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('logs', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('user_type', models.CharField(max_length=255)),
                ('login_time', models.DateTimeField()),
                ('logout_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_activity_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserLogs',
            fields=[
                ('logs', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('user_type', models.CharField(max_length=255)),
                ('login_time', models.DateTimeField()),
                ('logout_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_logs',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='admin',
            table='admin',
        ),
        migrations.AlterModelTable(
            name='announcement',
            table='announcement',
        ),
        migrations.AlterModelTable(
            name='dataprofiling',
            table='dataprofiling',
        ),
        migrations.AlterModelTable(
            name='healthworker',
            table='healthworker',
        ),
        migrations.AlterModelTable(
            name='predictiveanalytics',
            table='predictiveanalytics',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
        migrations.AlterModelTable(
            name='seniorcitizen',
            table='seniorcitizen',
        ),
        migrations.AlterModelTable(
            name='smsnotification',
            table='smsnotification',
        ),
    ]
