# Generated by Django 5.1 on 2024-10-12 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seniorapp', '0007_useractivitylog_userlogs_alter_admin_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=255)),
                ('score', models.FloatField(default=1.0)),
                ('prediction_rank', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('citizen', models.ForeignKey(db_column='citizen_id', on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='seniorapp.seniorcitizen')),
            ],
            options={
                'verbose_name': 'Predicted Disease',
                'verbose_name_plural': 'Predicted Diseases',
                'db_table': 'predicted_diseases',
            },
        ),
    ]
