# Generated by Django 5.1 on 2024-10-12 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seniorapp', '0008_predicteddisease'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predicteddisease',
            options={'managed': False},
        ),
    ]
