# Generated by Django 5.1 on 2024-10-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seniorapp', '0010_seniorcitizendiseaseview'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_disease', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'disease_count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeniorCitizenView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('health_condition', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('treatments', models.CharField(max_length=355)),
                ('checkups', models.CharField(max_length=355)),
                ('created_at', models.DateTimeField()),
                ('created_date', models.DateField()),
                ('created_week', models.CharField(max_length=20)),
                ('created_month', models.CharField(max_length=20)),
                ('created_year', models.CharField(max_length=4)),
                ('created_week_number', models.IntegerField()),
            ],
            options={
                'db_table': 'seniorcitizen_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TopCheckupsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkups', models.CharField(max_length=255)),
                ('checkup_count', models.IntegerField()),
            ],
            options={
                'db_table': 'top_checkups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TopHealthConditionsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_condition', models.CharField(max_length=255)),
                ('condition_count', models.IntegerField()),
            ],
            options={
                'db_table': 'top_health_conditions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TopPredictedDiseasesView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=255)),
                ('disease_count', models.IntegerField()),
            ],
            options={
                'db_table': 'top_predicted_diseases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TopTreatments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatments', models.CharField(max_length=255)),
                ('condition_count', models.IntegerField()),
            ],
            options={
                'db_table': 'top_treatments',
                'managed': False,
            },
        ),
    ]
